# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: continuumio/miniconda3:latest

clone:
  lfs: true

pipelines:
  default:
    - step: # Run tests
        name: Run tests.
        caches:
          - conda
          - pip
        script:
          - conda env update -n wolf --file env.yml
          - conda activate wolf
          - pip install .
          - pytest -v unit_test/

definitions:
   caches:
     conda: ~/.conda/envs/wolf
     codatarballs: /opt/conda/pkgs